alpha: 0.4
ann_root: annotation
batch_size_test: 64
batch_size_train: 12
dataset: retrieval_rstp
image_root: datasets/RSTPReid/imgs
image_size: 224
init_lr: 0.0001
k_test: 32
max_epoch: 20
min_lr: 0
negative_all_rank: true
pretrained: /root/autodl-tmp/CADA/output/CUHK/checkpoint_best_RSTP.pth
queue_size: 3600
vit: base
vit_ckpt_layer: 6
vit_grad_ckpt: true
weight_decay: 0.05
