alpha: 0.4
ann_root: annotation
batch_size_test: 64
batch_size_train: 24
dataset: retrieval_cuhk
image_root: datasets/CUHK-PEDES/imgs
image_size: 224
init_lr: 1.0e-05
k_test: 16
max_epoch: 30
min_lr: 0
negative_all_rank: true
pretrained: checkpoint/model_base.pth
queue_size: 3600
vit: base
vit_ckpt_layer: 4
vit_grad_ckpt: true
weight_decay: 0.05
